### ISSUE TITLE
Gemfile.lock

### ISSUE THREAD

**Issue by KazimieraLuce** [castle-crew/chess-group-project#8]
This has merge conflicts for me. Is anyone else running into this?

When I submit my next pull request, I'll commit the new Gemfile.lock I generated and see if that solves the problem.

**Comment by ZoeBKramer** [comment]
Just checked the `Gemfile.lock` and looks like there's a merge conflict in there for me too.

**Comment by KazimieraLuce** [comment]
OK, I'm going to make a pull request in a few minutes. We shall see if that version solves the problem.

**Comment by Monchkrit** [comment]
Hi, I delete the Gemfile.lock and run a bundle install. That fixes the problem. It would be nice to have it fixed on master origin.
